### PR TITLE
Adding support for selection using Tab key.

### PR DESCRIPTION
**Pull request by drewby**
Thanks for the great library. I needed the ability to use Tab for completion.

### CODE REVIEW

**Comment by ericgio** [comment]
Great suggestion. Seems like this should just be part of the core functionality and not require a prop, what do you think?

**Comment by drewby** [comment]
I was worried about breaking existing app behaviors when people update to latest version. So I guess there are some options
1) remove the property and just make it the core behavior
2) keep the prop but change the default to True
3) keep the it as is
Let me know what you think is best and I can update the pull request. Looks like I also clumsily checked in with eslint errors so will fix those too.

**Comment by ericgio** [comment]
My vote would be to make it part of the core functionality and not require use of a prop. A couple other things:

- Did you test this functionality with multi-selection?
- Ideally, I think it would be better to put the functionality in the input components rather than the main typeahead component, since this feels more like a behavior of the input.

**Comment by drewby** [comment]
Ok, I'll look into placing the functionality in the input components. No, I did not test with multi-selection but will do so.. Thanks!

**Comment by ericgio** [comment]
I went ahead and added this in v0.6.3. Let me know if the behavior is what you had in mind.

**Comment by emilsoman** [comment]
It would have been nice if this was a prop so users could override which keys would result in a selection.

**Comment by ericgio** [comment]
What other keys would you want to support?

**Pull request closed without merging**
