### PR TITLE
parametrize types on Option

### PR DESCRIPTION
**Pull request by ianatha**
see issue #704

### CODE REVIEW

**Comment by ericgio** [comment]
Hey @ianatha, thanks for the PR! I'm not sure why the CI actions aren't running against your PR here, but it looks like this change is triggering a bunch of type errors, which I see in your fork.

**Comment by ianatha** [comment]
Because the action is trying to publish a package from a non-main branch.

**Comment by ericgio** [comment]
> Because the action is trying to publish a package from a non-main branch

Got it, thanks. The change still triggers failures though.

**Comment by ianatha** [comment]
You’re right, and I should have clarified my intent with the PR—I apologise for the miscommunication. 
I wanted to ensure we agreed on what the top-level type safe API looks like before cascading the parametric type down.

**Comment by ericgio** [comment]
> I wanted to ensure we agreed on what the top-level type safe API looks like before cascading the parametric type down

@ianatha is there any particular part of the change you wanted to discuss or that needs my attention?

Also, I unintentionally closed the PR by deleting another branch; would you mind please re-submitting the PR? I apologize for that, and thank you for taking the time to work on this!

**Pull request closed without merging**
