### PR TITLE
Allow return/enter to be used to select proposed hintText

### PR DESCRIPTION
**Pull request by MHultman**
Would like to be able to use return to select the top result.

### CODE REVIEW

**Comment by suresh-muthu** [comment]
👍  Can we merge this PR please?

**Comment by tonycode** [comment]
A couple of times I've also come across a need to use the return key for the only one suggested item selection.
Yes, in most projects UX is designed to use the tab key, or highlight the item with arrow keys and then you can press return.
But there are some legacy projects where there is a requirement to keep old behavior - and it is to accept the only one item even you haven't highlighted it with arrows... In such situation you need to clone this repo and apply similar patch... It's not a lightweight solution)

Maybe we can some special attr (let's say, `acceptFirstItemOnReturn`) with default value to `false` ?

**Comment by MHultman** [comment]
@tonycode I had that exact idea at first, but implemented the shortcut version.
Fixing the prop tonight when Im of work. 
Thx for the feedback!

**Comment by ericgio** [comment]
Added `selectHintOnEnter` prop in v2.0.0-alpha.1

**Pull request closed without merging**
