### PR TITLE
Add: Bootstrap 4 support

### PR DESCRIPTION
**Pull request by Kuzmin**
Supporting Bootstrap 4 might be way off in the future for you. However, I needed it for my own project, so I thought I would put this diff up here so that others who also need it can find it easily. :)

Thanks!

### CODE REVIEW

**Comment by ericgio** [comment]
Hey, thanks! I'll revisit this after v4 is out of alpha.

**Comment by MiLk** [comment]
Code changes LGTM

**Comment by herecydev** [comment]
@ericgio I would love to get this shipped as a prerelease build. If you're happy with that?

**Comment by ericgio** [comment]
I'm hesitant to do this at the moment given Bootstrap 4 is still in alpha. It means extra overhead for me, and would only be useful for a small subset of people. I'd like to allow developers to specify their own menu to decouple this component from the various Bootstrap versions.

For now, can you either use @Kuzmin's [version](https://www.npmjs.com/package/react-bootstrap-4-typeahead) or fork the repository?

**Comment by herecydev** [comment]
Aplogies I didn't see he shipped an npm package. That will do for now, thanks.

**Comment by Kuzmin** [comment]
Hey there guys! Yeah I shipped this as an NPM package because that felt like the fastest way to use this in my own projects. I think @ericgio has shipped like 30 commits since then, so just make sure that you're not missing any features by using my fork 😄

**Comment by ericgio** [comment]
Closing this PR and tracking in #131.

**Pull request closed without merging**
