### PR TITLE
enable tab completion if used as controlled input

### PR DESCRIPTION
**Pull request by tkloht**
Hi,
I am using the async typeahead as a controlled input, by setting the `selected` prop. I noticed that accepting an option by pressing tab did not work, and after looking at the source found that this feature is excluded for the case that there is "currently a selection".
There is probably a good reason for this, but right now I don't see why it would be necessary. With my changes it seems to work perfectly for me.

### CODE REVIEW

**Comment by ericgio** [comment]
Hello, and thank you for contributing! Just to clarify, I don't think this issue has anything to do with using the typeahead as a controlled or uncontrolled component. I'm guessing you're using it as a tokenizer (`multiple={true}`), which currently doesn't support the hinting and tab-complete feature. The issue is being tracked in #88.

**Comment by t-obi** [comment]
I'm not using `multiple={true}`, at first i thought that might be the issue too but it doesn't seem so. My first attempt at getting the tab completion working was setting `multiple={false}` to double check, but it had no effect.

I am setting the `selected` prop to the current input thought, let's say i have a list countries as options and start typing `fra`, then we keep `fra`in local state and set the `selected`prop to `fra`.

Now i can click on `France` to select it, this works fine. I can also highlight `France` and select it with `enter`.  But I can't use tab instead of enter.

When I looked at your code I saw that you explicitly exclude the case where something is already set in selected when handling the tab key. If you look at my changes it is exactly the few lines that i have changed. If you set `selected` to display an input this would always would always be true - your comment says "there is a current selection", this is not technically true because it is only an arbitrary string and not a country from our list of options. But it would always evaluate to true. I hope this makes sense.

I also don't see why it would be necessary to prevent selecting an option if there is already some value in `selected`. If can think of any case where this would be problematic please let me know.

Currently we are using a version of the component with my changes and there have not been any problems. I have not tested if there are any problems when using it as an uncontrolled input, or with multiple selections for example.

**Comment by ericgio** [comment]
> I am setting the selected prop to the current input thought, let's say i have a list countries as options and start typing `fra`, then we keep `fra` in local state and set the `selected` prop to `fra`.

That's not the right way to use the component. `fra` is not a selection and therefore should not be passed to `selected`. You should only be passing the results of `onChange` to `selected`.

**Comment by t-obi** [comment]
I don't see why it I can't use the component like I do - I need to display a value in the input without entering it, and this is the only way to do it. Also it's not as if this doesn't work at all, it works perfectly fine except of the tab completion. And the missing tab completion seems like a bug to me because i can't see a reason why the check i have removed would be necessary in the first place.

While typing this i also noticed that only using the results of `onchange` to set `selected` doesn't really solve the problem. If you have an option A that is contained in an option B, select option A then try to select option B with tab it will not work. I know that you dispatch onChange with an empty array when you change the input, but in this case you are able to select another option without changing the input first. Only in this case you are not able to use tab to select it.

I have created a small example to illustrate my point: http://www.kloht.com/bs-typeahead-test/
source is available at https://github.com/t-obi/bs-typeahead-test

by default you have an uncontrolled input
if you check the first checkbox you have a controlled input as described by me initially
if you check the second checkbox `onInputChange` will not be used to set `selected`

to reproduce the issue described in this comment:
- activate both checkboxes
- enter "congo" and select congo
- focus the field again. do not change the text input
- navigate to option "Congo, the Democratic Republic of the" with arrow keys
- hit enter to select "Congo, the Democratic Republic of the". it will not work

**Comment by ericgio** [comment]
> I don't see why it I can't use the component like I do

Because it's not currently designed to work the way you're using it.

> I need to display a value in the input without entering it

Why? I'd like to understand the use case for programmatically displaying arbitrary text (ie: not one of the possible selections) in the input.

> - activate both checkboxes
> - enter "congo" and select congo
> - focus the field again. do not change the text input
> - navigate to option "Congo, the Democratic Republic of the" with arrow keys
> - hit enter to select "Congo, the Democratic Republic of the". it will not work

I followed these repro steps on your test site and it worked fine for me. I don't understand the issue you're describing.

**Comment by t-obi** [comment]
About the use case:
We have a website with multiple tabs, on one tab there is a typeahead.
When you move to another tab the typeahead gets unmounted, losing its state.
When you go back to the previous tab we want to keep the input, even if no option has been selected yet.

about reproducing:
I had a typo in my description, in the last step try to select it with tab not with enter.
This is what happens:
6oup2f3rjw

**Comment by ericgio** [comment]
I did some further investigation and the issue you're describing isn't a bug, it's expected. Tab completion only works when there's a hint. Try following the steps you describe and deleting a character or 2 when you key down to the desired option. This will display a hint and hitting tab will work. Otherwise, you need to hit enter, not tab, as the latter will blur the input.

As to your other request about programmatically populating the input with an arbitrary value, I don't currently have plans to add a public API for that. If you absolutely MUST have that functionality, I'd recommend just grabbing the input dom node and setting the value. However, you should consider this undocumented and highly unstable. I have no idea what effects it will otherwise have on the component.

**Comment by tkloht** [comment]
Makes sense now that you explained it. We ended up just using a forked version with this pr because it does exactly what we needed. I understand that you do not plan to extend the API, I think our requirements were very... special and it doesn't really make sense to support that. Thanks for the detailed reply and have a nice day!

**Pull request closed without merging**
