### PR TITLE
Make role of filterBy clearer in docs

### PR DESCRIPTION
**Pull request by wetneb**
**What issue does this pull request resolve?**
The description of the `filterBy` callback is not clear enough.

**What changes did you make?**
I added a description of the arguments and return value expected from this callback.

**Is there anything that requires more attention while reviewing?**
I don't think so.

### CODE REVIEW

**Comment by ericgio** [comment]
Hi @wetneb, thanks for the pull request. The docs have a [dedicated section on filtering](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby) with a more in-depth description of the API. The props table is meant to be more of an overview of the available props.

**Comment by wetneb** [comment]
I am not sure what would be the harm in adding that information there too? Would you prefer it to be a direct link to https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby maybe?

Overall my point is it is a bit frustrating for the user to read about "a callback" without knowing what its signature is. I think it is reasonable to expect that a list of props also documents the types of each of these props.

**Comment by ericgio** [comment]
Yes, I think a direct link would help surface the in-depth docs. Adding the actual signature could be a more concise way presenting the information directly (eg: `(option: Object|String, props: Object) => boolean`), but it doesn't look like that works very well within table markdown.

**Comment by ericgio** [comment]
This is great, thank you.

**Pull request merged**
