### PR TITLE
add typescript typings

### PR DESCRIPTION
**Pull request by ehartford**
https://github.com/ericgio/react-bootstrap-typeahead/issues/116

### CODE REVIEW

**Comment by ericgio** [comment]
Thanks for the PR. Any suggestions on how this might be decoupled from the rest of the module? I don't use Typescript myself so these typings aren't useful to me and I don't want to maintain them when adding new props.

**Comment by ericgio** [comment]
I'd say feel free to contribute to that repository and publish the package, then. It will certainly be useful to some subset of people using this component.

**Comment by mtrivolli** [comment]
If I may suggest... The typings are missing the AsyncTypeahead. I would add the following:
```typescript
interface AsyncTypeaheadProps extends TypeaheadProps {
    onSearch?: (query: string) => void
}

export var AsyncTypeahead: React.ClassicComponentClass<AsyncTypeaheadProps>
```

**Comment by sztobar** [comment]
@ehartford  mind If I create PR with Your typings to [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped)? I haven't saw any initiative taken to Definitely Typed since You mentioned it, and I would very much appreciate types for typeahead.

**Comment by ehartford** [comment]
Please by all means, much appreciated.  (and i didn't write them i only
wrote a PR)

**Comment by 8enSmith** [comment]
Are these changes going to be merged soon?  I'm working with a project that uses Typescript and I can't really progress until these changes have been merged.

**Comment by ehartford** [comment]
The package maintainer has declined to accept TypeScript types into the package.

Someone will need to create and maintain a separate package.

**Comment by Guymestef** [comment]
PR made on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22296

**Pull request closed without merging**
