### PR TITLE
Display menu

### PR DESCRIPTION
**Pull request by michelre**
Thanks for your great job!

I needed a way to hide the dropdown menu when the input field is empty. So I added a boolean props to do that!

### CODE REVIEW

**Comment by ericgio** [comment]
Can you tell me a little more about your use case? While I could potentially see a case for externally controlling the menu visibility, your implementation feels a bit specific. My feeling is that there could be a general `showMenu` prop, and you could use the `onInputChange` hook to fire it when the text string is empty.

**Comment by michelre** [comment]
My case was simple but very specific, you're right. In fact, I didn't want the menu to be automatically displayed when the user click on the input field and when this field is empty (http://getbootstrap.com/2.3.2/javascript.html#typeahead)

My first idea was to control this option with a boolean since it seemed more natural to me. But your idea is great!!

Thanks! :)

**Comment by ericgio** [comment]
Ah actually, it sounds like you're saying you don't want to display the menu on focus by default, just like the twitter bootstrap example. So in that case, I guess the callback makes less sense. Someone just opened an issue with a similar use case, so it seems valid.

**Comment by michelre** [comment]
Ok, let me remove the callback, you're right, it doesn't make sense anymore.

**Comment by esthersweon** [comment]
@ericgio just checking in – will this be merged in soon? Waiting on this functionality before using in a project.

**Comment by ericgio** [comment]
Sorry for the delay, I'm out of the country on vacation for a couple weeks. I'll do my best to get it in sometime next week when I'm back.

**Comment by ericgio** [comment]
`minLength` prop added in v0.6.0

**Pull request closed without merging**
